### ISSUE TITLE
IllegalArgumentException: Structure exceeds provided memory bounds

### ISSUE THREAD

**Issue by heymjo** [dblock/oshi#104] opened 2015-12-03 07:28 UTC
Hi,

I have deployed a small servlet on my weblogic instance to display some stats using this library. Getting below exeception however. The funny thing is that the same code from a unit test runs fine and returns what i intended:

Microsoft Windows 7 SP1
Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz

```
java.lang.IllegalArgumentException: Structure exceeds provided memory bounds
	at com.sun.jna.Structure.useMemory(Structure.java:287)
	at com.sun.jna.Pointer.getValue(Pointer.java:369)
	at com.sun.jna.Structure.readField(Structure.java:601)
	at com.sun.jna.Structure.read(Structure.java:479)
	at com.sun.jna.Structure.toArray(Structure.java:1212)
	at com.sun.jna.platform.win32.Kernel32Util.getLogicalProcessorInformation(Kernel32Util.java:544)
	at oshi.hardware.platform.windows.WindowsCentralProcessor.calculateProcessorCounts(WindowsCentralProcessor.java:156)
	at oshi.hardware.platform.windows.WindowsCentralProcessor.(WindowsCentralProcessor.java:126)
	at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.getProcessor(WindowsHardwareAbstractionLayer.java:40)
```
I am running on jdk version 1.7.0_79 64-bit, Weblogic Server 12.1.2.0.0

Any ideas ?

**Comment by dbwiddis** [comment] 2015-12-03 16:39
No ideas from this end.  This looks like a possible bug in JNA... all oshi does is call `Kernel32Util.getLogicalProcessorInformation()` which according to the javadoc is a "Convenience method to get the processor information. Takes care of auto-growing the array."   Apparently it doesn't. 

I'd suggest posting this question on the [JNA users google group](https://groups.google.com/forum/#!forum/jna-users).

I assume you have fewer than 64 processors, right?  This particular implementation can't handle larger.

**Comment by dblock** [comment] 2015-12-04 04:53
I would "move" this bug into JNA, try to repro it there in a unit test.

**Comment by heymjo** [comment] 2015-12-04 07:10
Well as i said, it works fine in the unit test just not under weblogic application server. Thanks for the pointers i will move this to the suggested jna google group.

**Comment by dbwiddis** [comment] 2015-12-05 20:40
@heymjo ... I just found this in the JNA issues:  https://github.com/java-native-access/jna/issues/496

Looks like the `Structure.toArray()` method assumes that there is at least one element in the array, and you are getting the exception because you have a zero sized array.

Apparently in your setup you have 0 physical processors.

So the question becomes, should Oshi catch that exception (and return 0) or should the `Kernel32Util.getLogicalProcessorInformation()` method return an empty array?    (Or both, even if the oshi behavior is a temporary fix until JNA is updated.)  I'm going to reopen this issue to track a resolution one way or the other, but hope @dblock can chime in on which side of the fence we need to fix this on.

**Comment by dbwiddis** [comment] 2015-12-05 21:29
Actually, on further research, the underlying windows function is guaranteed to return at least one element in the array, so my above theory is invalid.  Phooey.

**Comment by heymjo** [comment] 2015-12-06 07:45
To be honest I wrapped my code in a try catch and set the info to n/a if
for some reason jna bombs out. I strongly suspect weblogic has something to
do with it, but did not feel to go down that timesink rabbit hole again.
Happy to try any suggestions though..

Op za 5 dec. 2015 22:29 schreef dbwiddis <notifications@github.com>:

**Comment by dbwiddis** [comment] 2015-12-06 16:50
Unfortunately that means you can't use any of the CPU load code either.  I can catch the exception earlier for you so we only lose that one value (physical processor count). 

If you don't mind, can I produce a version of that code with copious log statements to try to figure out what's happening on  Weblogic?  All you'd have to do is run it....

**Comment by heymjo** [comment] 2015-12-06 19:32
Sure that would be great no problem, just let me know where to grab it from.

**Comment by dbwiddis** [comment] 2015-12-06 21:48
OK, I've caught the exception and replicated the Kernel32Util code with some println statements to let me trace the calculations.  If you're using jar files, you can grab the 2.1-SNAPSHOT [here](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=com.github.dblock&a=oshi-core&v=2.1-SNAPSHOT&e=jar).  With maven, point it to 2.1-SNAPSHOT in the Sonatype shapshots repository.

**Comment by heymjo** [comment] 2015-12-07 11:00
oh well as it goes the error is no longer present now. no idea what happened, but 2.0 and 2.1-SNAPSHOT work fine now. <sigh> not sure what to do with this issue. In case the problem surfaces again i will retry with the snapshot version.

**Comment by dbwiddis** [comment] 2015-12-07 19:41
Mysterious!

I'll leave the try/catch in on the oshi side for the next release and close this issue... I'll clean up those debug lines and put in a proper log warning instead when 2.1 (or 2.0.1) comes out.

**Closed by dbwiddis** 2015-12-07 19:41 UTC

**Comment by dblock** [comment] 2015-12-09 12:00
This looks like a real bug to me, but it's possible that the issue is actually not in this call and that another prior call corrupts memory causing something to fail as a side-effect. These are a bit hard to debug, but obviously needs a consistent repro.

**Comment by dbwiddis** [comment] 2015-12-09 23:56
So, I tried to engage in [Rubber duck debugging](https://en.wikipedia.org/wiki/Rubber_duck_debugging) of this today and noted that the line number in `Structure.java` for the `toArray()` call from the stack trace has a line that doesn't match the current version of JNA (4.2.1):
```
    at com.sun.jna.Structure.toArray(Structure.java:1212)
```
`toArray()` in recent versions starts in the 1400's.

A bit of delving into the history of the Structure class shows that in version 3.4.1, that method contained line 1212.

So, @heymjo ... can you confirm you're using the latest (4.2.1) version of JNA?  If not, I suspect that may be the culprit.

**Comment by heymjo** [comment] 2015-12-10 07:51
Thanks. 

I started my instance this morning and verified everything was still working fine , it  was.
Then i enabled jrebel and the error appeared again. So then i disabled jrebel again and restarted but the error stayed ! 

Could it be that this agent is somehow overwriting a jna dll somewhere in a temp dir ? And that this temp dir gets cleared out upon restart or something, would explain the weird behavior maybe...

**Comment by dbwiddis** [comment] 2015-12-10 15:26
I'm not familiar with jrebel but a quick look at it indicates it dynamically reloads classes while you're running.

I strongly suspect you're loading an out of date (3.5.1) version of the Structure class somehow, and you need to dig into your dependency management to figure out where it's coming from.

**Comment by heymjo** [comment] 2015-12-10 18:46
At some point i remember seeing some debug flags for jna, that would give
some output where the dll is loaded from. I'll try and dig that up again
and see if it gives some helpful diag

Jorg

**Comment by phoenixjiangnan** [comment] 2015-12-17 07:26
I also hit this when upgrading from 1.5.2 to 2.0. I'll upgrade our jna from 4.1 to 4.2.1 to give a try.

I'm also wondering if 2.1-SNAPSHOT has the fix and is production-ready?

Thanks!

**Comment by dbwiddis** [comment] 2015-12-17 11:19
The odd thing is that block of code is the same in 1.5.2 and 2.0. Although Oshi does depend on JNA 4.2.1 so that part isn't surprising. 

2.1-snapshot does catch that error and spit out a bunch of debug lines.  Not really a "fix" but otherwise just as porosity ion ready as 2.0

**Comment by dbwiddis** [comment] 2015-12-17 11:20
Production ready.  Dang autocorrect.

**Comment by dbwiddis** [comment] 2015-12-31 05:33
I'm planning on removing the debugging code since I believe the error is caused by using an old version of JNA.
